defaults:
  output_dir: "output"
  venv: ".venv"
  tesseract_lang: "spa"

brand_configs:
  vodafone: "config/vodafone.yaml"
  lynks-tic: "config/lynks-tic.yaml"
  lynks-tic-b2mobile: "config/lynks-tic-b2mobile.yaml"